# Form implementation generated from reading ui file 'day2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class DayEditWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 766)
        MainWindow.setStyleSheet('color: black;')
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 851, 781))
        self.frame.setStyleSheet("background: rgb(144, 144, 144);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(20, 20, 811, 731))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tasks = QtWidgets.QListWidget(parent=self.widget)
        self.tasks.setStyleSheet("background: white;\n"
"border-radius: 20px;")
        self.tasks.setObjectName("tasks")
        self.gridLayout.addWidget(self.tasks, 0, 0, 1, 3)
        self.task_edit_name = QtWidgets.QLineEdit(parent=self.widget)
        self.task_edit_name.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.task_edit_name.setFixedHeight(50)
        self.task_edit_name.setReadOnly(False)
        self.task_edit_name.setObjectName("task_edit_name")
        self.gridLayout.addWidget(self.task_edit_name, 1, 2, 1, 1)
        self.create_task_name = QtWidgets.QLineEdit(parent=self.widget)
        self.create_task_name.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.create_task_name.setReadOnly(False)
        self.create_task_name.setObjectName("create_task_name")
        self.create_task_name.setFixedHeight(50)
        self.gridLayout.addWidget(self.create_task_name, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 2, 1)
        self.task_edit_comment = QtWidgets.QLineEdit(parent=self.widget)
        self.task_edit_comment.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.task_edit_comment.setReadOnly(False)
        self.task_edit_comment.setObjectName("task_edit_comment")
        self.task_edit_comment.setFixedHeight(50)
        self.gridLayout.addWidget(self.task_edit_comment, 2, 2, 1, 1)
        self.create_task_comment = QtWidgets.QLineEdit(parent=self.widget)
        self.create_task_comment.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.create_task_comment.setReadOnly(False)
        self.create_task_comment.setObjectName("create_task_comment")
        self.create_task_comment.setFixedHeight(50)
        self.gridLayout.addWidget(self.create_task_comment, 3, 0, 1, 1)
        self.task_edit_progress = QtWidgets.QLineEdit(parent=self.widget)
        self.task_edit_progress.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.task_edit_progress.setReadOnly(False)
        self.task_edit_progress.setObjectName("task_edit_progress")
        self.task_edit_progress.setFixedHeight(50)
        self.gridLayout.addWidget(self.task_edit_progress, 3, 2, 1, 1)
        self.create_task = QtWidgets.QPushButton(parent=self.widget)
        self.create_task.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_task.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.create_task.setIconSize(QtCore.QSize(50, 50))
        self.create_task.setObjectName("create_task")
        self.create_task.setFixedHeight(50)
        self.gridLayout.addWidget(self.create_task, 4, 0, 1, 1)
        self.change_task = QtWidgets.QPushButton(parent=self.widget)
        self.change_task.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.change_task.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.change_task.setIconSize(QtCore.QSize(50, 50))
        self.change_task.setObjectName("change_task")
        self.change_task.setFixedHeight(50)
        self.gridLayout.addWidget(self.change_task, 4, 2, 1, 1)
        self.delete_task = QtWidgets.QPushButton(parent=self.widget)
        self.delete_task.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_task.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.delete_task.setIconSize(QtCore.QSize(50, 50))
        self.delete_task.setFixedHeight(50)
        self.delete_task.setObjectName("delete_task")
        self.gridLayout.addWidget(self.delete_task, 5, 0, 1, 3)
        self.back = QtWidgets.QPushButton(parent=self.widget)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.back.setIconSize(QtCore.QSize(50, 50))
        self.back.setObjectName("back")
        self.back.setFixedHeight(50)
        self.gridLayout.addWidget(self.back, 6, 0, 1, 3)
        MainWindow.setCentralWidget(self.frame)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ambitify"))
        self.task_edit_name.setPlaceholderText(_translate("MainWindow", "Час/імʼя"))
        self.create_task_name.setPlaceholderText(_translate("MainWindow", "Час/імʼя"))
        self.label.setText(_translate("MainWindow", "Примітка:\n"
"Залиште поле пустим,\n"
"якщо не хочете\n"
"змінювати\n"
"якийсь параметр"))
        self.task_edit_comment.setPlaceholderText(_translate("MainWindow", "Коментар"))
        self.create_task_comment.setPlaceholderText(_translate("MainWindow", "Коментар"))
        self.task_edit_progress.setPlaceholderText(_translate("MainWindow", "Прогресс"))
        self.create_task.setText(_translate("MainWindow", "Створити завдання"))
        self.change_task.setText(_translate("MainWindow", "Змінити завдання"))
        self.delete_task.setText(_translate("MainWindow", "Видалити завдання"))
        self.back.setText(_translate("MainWindow", "Назад"))
