# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from const import VERSION


class MainWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(845, 611)
        MainWindow.setStyleSheet("color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 851, 611))
        self.frame.setStyleSheet("background: rgb(124, 124, 124);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.tabShow = QtWidgets.QStackedWidget(parent=self.frame)
        self.tabShow.setGeometry(QtCore.QRect(220, 10, 611, 591))
        self.tabShow.setStyleSheet("background: rgb(144, 144, 144);\n"
"border-radius: 20px;")
        self.tabShow.setObjectName("tabShow")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(200, 0, 211, 61))
        self.label_2.setStyleSheet("color: white;\n"
"font-weight: 800;\n"
"font-size: 50px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setGeometry(QtCore.QRect(130, 60, 351, 61))
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.calendar_2 = QtWidgets.QPushButton(parent=self.page)
        self.calendar_2.setGeometry(QtCore.QRect(30, 130, 271, 71))
        self.calendar_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.calendar_2.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.calendar_2.setIconSize(QtCore.QSize(50, 50))
        self.calendar_2.setObjectName("calendar_2")
        self.settings_2 = QtWidgets.QPushButton(parent=self.page)
        self.settings_2.setGeometry(QtCore.QRect(310, 130, 271, 71))
        self.settings_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settings_2.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.settings_2.setIconSize(QtCore.QSize(50, 50))
        self.settings_2.setObjectName("settings_2")
        self.tabShow.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setGeometry(QtCore.QRect(180, 0, 251, 61))
        self.label_4.setStyleSheet("color: white;\n"
"font-weight: 800;\n"
"font-size: 50px;")
        self.label_4.setObjectName("label_4")
        self.days = QtWidgets.QListWidget(parent=self.page_2)
        self.days.setGeometry(QtCore.QRect(20, 70, 571, 241))
        self.days.setStyleSheet("background: white;\n"
"border-radius: 20px;")
        self.days.setObjectName("days")
        self.create_new_day = QtWidgets.QPushButton(parent=self.page_2)
        self.create_new_day.setGeometry(QtCore.QRect(340, 420, 261, 71))
        self.create_new_day.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_new_day.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.create_new_day.setIconSize(QtCore.QSize(50, 50))
        self.create_new_day.setObjectName("create_new_day")
        self.new_day_name = QtWidgets.QLineEdit(parent=self.page_2)
        self.new_day_name.setGeometry(QtCore.QRect(340, 340, 261, 71))
        self.new_day_name.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.new_day_name.setObjectName("new_day_name")
        self.delete_day = QtWidgets.QPushButton(parent=self.page_2)
        self.delete_day.setGeometry(QtCore.QRect(10, 420, 261, 71))
        self.delete_day.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_day.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.delete_day.setIconSize(QtCore.QSize(50, 50))
        self.delete_day.setObjectName("delete_day")
        self.open_day = QtWidgets.QPushButton(parent=self.page_2)
        self.open_day.setGeometry(QtCore.QRect(10, 340, 261, 71))
        self.open_day.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.open_day.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.open_day.setIconSize(QtCore.QSize(50, 50))
        self.open_day.setObjectName("open_day")
        self.rename_day_name = QtWidgets.QLineEdit(parent=self.page_2)
        self.rename_day_name.setGeometry(QtCore.QRect(10, 510, 261, 71))
        self.rename_day_name.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.rename_day_name.setObjectName("rename_day_name")
        self.rename_day = QtWidgets.QPushButton(parent=self.page_2)
        self.rename_day.setGeometry(QtCore.QRect(290, 510, 311, 71))
        self.rename_day.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.rename_day.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.rename_day.setIconSize(QtCore.QSize(50, 50))
        self.rename_day.setObjectName("rename_day")
        self.tabShow.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_5 = QtWidgets.QLabel(parent=self.page_3)
        self.label_5.setGeometry(QtCore.QRect(120, 0, 391, 61))
        self.label_5.setStyleSheet("color: white;\n"
"font-weight: 800;\n"
"font-size: 50px;")
        self.label_5.setObjectName("label_5")
        self.save_settings = QtWidgets.QPushButton(parent=self.page_3)
        self.save_settings.setGeometry(QtCore.QRect(10, 150, 281, 71))
        self.save_settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_settings.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.save_settings.setIconSize(QtCore.QSize(50, 50))
        self.save_settings.setObjectName("save_settings")
        self.chose = QtWidgets.QPushButton(parent=self.page_3)
        self.chose.setGeometry(QtCore.QRect(320, 150, 281, 71))
        self.chose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.chose.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.chose.setIconSize(QtCore.QSize(50, 50))
        self.chose.setObjectName("chose")
        self.database_path = QtWidgets.QLineEdit(parent=self.page_3)
        self.database_path.setGeometry(QtCore.QRect(10, 70, 591, 71))
        self.database_path.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"padding-left: 5px;")
        self.database_path.setObjectName("database_path")
        self.source_code = QtWidgets.QPushButton(parent=self.page_3)
        self.source_code.setGeometry(QtCore.QRect(10, 510, 591, 71))
        self.source_code.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.source_code.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.source_code.setIconSize(QtCore.QSize(50, 50))
        self.source_code.setObjectName("source_code")
        self.version = QtWidgets.QLabel(parent=self.page_3)
        self.version.setGeometry(QtCore.QRect(220, 480, 161, 16))
        self.version.setStyleSheet("color: white;")
        self.version.setObjectName("version")
        self.tabShow.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_6 = QtWidgets.QLabel(parent=self.page_4)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 350, 61))
        self.label_6.setStyleSheet("color: white;\n"
"font-weight: 800;\n"
"font-size: 50px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_4)
        self.label_7.setGeometry(QtCore.QRect(130, 80, 351, 61))
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.back = QtWidgets.QPushButton(parent=self.page_4)
        self.back.setGeometry(QtCore.QRect(170, 290, 281, 71))
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        self.back.setIconSize(QtCore.QSize(50, 50))
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(parent=self.page_4)
        self.label.setGeometry(QtCore.QRect(120, 250, 381, 31))
        self.label.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(parent=self.page_4)
        self.label_8.setGeometry(QtCore.QRect(80, 190, 481, 31))
        self.label_8.setStyleSheet("color: white;\n"
"font-size: 20px;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.page_4)
        self.label_9.setGeometry(QtCore.QRect(220, 160, 161, 31))
        self.label_9.setStyleSheet("color: white;\n"
"font-size: 25px;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.page_4)
        self.label_10.setGeometry(QtCore.QRect(100, 220, 401, 31))
        self.label_10.setStyleSheet("color: white;\n"
"font-size: 25px;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tabShow.addWidget(self.page_4)
        self.menu = QtWidgets.QFrame(parent=self.frame)
        self.menu.setGeometry(QtCore.QRect(10, 10, 191, 591))
        self.menu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.menu.setStyleSheet("background: rgb(144, 144, 144);\n"
"border-radius: 20px;")
        self.menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu.setObjectName("menu")
        self.menu_title = QtWidgets.QLabel(parent=self.menu)
        self.menu_title.setGeometry(QtCore.QRect(20, 0, 151, 51))
        self.menu_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: 800;\n"
"font-size: 50px;")
        self.menu_title.setObjectName("menu_title")
        self.home = QtWidgets.QPushButton(parent=self.menu)
        self.home.setGeometry(QtCore.QRect(20, 60, 151, 71))
        self.home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"    padding-left: -5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home.setIcon(icon)
        self.home.setIconSize(QtCore.QSize(50, 50))
        self.home.setObjectName("home")
        self.calendar = QtWidgets.QPushButton(parent=self.menu)
        self.calendar.setGeometry(QtCore.QRect(20, 140, 151, 71))
        self.calendar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.calendar.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.calendar.setIcon(icon1)
        self.calendar.setIconSize(QtCore.QSize(50, 50))
        self.calendar.setObjectName("calendar")
        self.settings = QtWidgets.QPushButton(parent=self.menu)
        self.settings.setGeometry(QtCore.QRect(20, 500, 151, 71))
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settings.setStyleSheet("QPushButton {\n"
"    background: rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"    font-size: 10px;\n"
"padding-left: 5px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(134, 134, 134);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings.setIcon(icon2)
        self.settings.setIconSize(QtCore.QSize(50, 50))
        self.settings.setObjectName("settings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabShow.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ambitify"))
        self.label_2.setText(_translate("MainWindow", "Головна"))
        self.label_3.setText(_translate("MainWindow", "Ambitify - це безкоштовний та open-source планер.\n"
"Ви можете планувати свої справи, та додавати\n"
"нові функції у планер"))
        self.calendar_2.setText(_translate("MainWindow", "Календар"))
        self.settings_2.setText(_translate("MainWindow", "Налаштування"))
        self.label_4.setText(_translate("MainWindow", "Календар"))
        self.create_new_day.setText(_translate("MainWindow", "Створити новий день"))
        self.new_day_name.setPlaceholderText(_translate("MainWindow", "Введіть сюди імʼя нового дня"))
        self.delete_day.setText(_translate("MainWindow", "Видалити день"))
        self.open_day.setText(_translate("MainWindow", "Відкрити день"))
        self.rename_day_name.setPlaceholderText(_translate("MainWindow", "Введіть сюди нове імʼя дня"))
        self.rename_day.setText(_translate("MainWindow", "Змінити назву дня"))
        self.label_5.setText(_translate("MainWindow", "Налаштування"))
        self.save_settings.setText(_translate("MainWindow", "Зберегти"))
        self.chose.setText(_translate("MainWindow", "Вибрати..."))
        self.database_path.setPlaceholderText(_translate("MainWindow", "Шлях до збереження бази данних"))
        self.source_code.setText(_translate("MainWindow", "Вихідний код..."))
        self.version.setText(_translate("MainWindow", f"Версія программи: {VERSION}"))
        self.label_6.setText(_translate("MainWindow", "Вихідний код"))
        self.label_7.setText(_translate("MainWindow", "Ambitify є безкоштовним та open-source планером,\n"
"який не слідкує за користувачем та не має реклами.\n"
"Тут посилання на код та утиліти программи:"))
        self.back.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "<a href=\'https://www.github.com/Andboogl/Ambitify\'>https://www.github.com/Andboogl/Ambitify</a>"))
        self.label_8.setText(_translate("MainWindow", "<a href=\'https://www.github.com/Andboogl/Ambitify-Database\'>https://www.github.com/Andboogl/Ambitify-Database</a>"))
        self.label_9.setText(_translate("MainWindow", "База данних"))
        self.label_10.setText(_translate("MainWindow", "Додаток (який ви зараз відкрили)"))
        self.menu_title.setText(_translate("MainWindow", "Меню"))
        self.home.setText(_translate("MainWindow", "  Головна"))
        self.calendar.setText(_translate("MainWindow", "  Календар"))
        self.settings.setText(_translate("MainWindow", "  Налаштування"))
